services:
  - type: web
    name: ec-profile-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BASE_URL
        value: https://entropyclient.onrender.com
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false